### ISSUE TITLE
Failed to pull V5 OC-CCI data from ERRDAP

### ISSUE THREAD

**Issue by annbel** [ropensci/rerddap#102]
hi,

I am trying to use rerdap to access the most recent daily OC-CCI data (list here https://coastwatch.pfeg.noaa.gov/erddap/search/index.html?page=1&itemsPerPage=1000&searchFor=cci) 

It does not seem possible to pull v5 data: pmlEsaCCI50OceanColorDaily, even though it is on ERRDAP. Checking with ed_search, reveals that the most recent versions are not there. is it possible to update to allow rerdap to get the v5 OC-CCI data?

ed_search('cci')
# A tibble: 6 x 2
  title                                                                       dataset_id      
  <chr>                                                                       <chr>           
1 ESA CCI Ocean Colour Product (CCI ALL-v4.2-8DAY), 0.04166666°, 1997-2020    pmlEsaCCI42Ocea~
2 ESA CCI Ocean Colour Product (CCI ALL-v3.1-DAILY), 0.04166666°, 1997-2018   pmlEsaCCI31Ocea~
3 ESA CCI Ocean Colour Product (CCI ALL-v3.1-8DAY), 0.04166666°, 1997-2018    pmlEsaCCI31Ocea~
4 ESA CCI Ocean Colour Product (CCI ALL-v3.1-MONTHLY), 0.04166666°, 1997-2018 pmlEsaCCI31Ocea~
5 ESA CCI Ocean Colour Product (CCI ALL-v4.2-DAILY), 0.04166666°, 1997-2019   pmlEsaCCI42Ocea~
6 ESA CCI Ocean Colour Product (CCI ALL-v4.2-MONTHLY), 0.04166666°, 1997-2020 pmlEsaCCI42Ocea~

**Comment by rmendels** [comment]
@annbel  The reason it does not show up in the search,  but does show up in the URL that you reference is that the default server in 'rerddap' is https://upwell.pfeg.noaa.gov/erddap.  If instead you do:

```r
test <- rerddap::ed_search('cci', url = "https://coastwatch.pfeg.noaa.gov/erddap/")
```

you will see that it does find the v5.   'gridddap()' will work just fine as long as you pass in the call the URL https://coastwatch.pfeg.noaa.gov/erddap/.  Look at the man pages for  'gridddap()' to see that.  If you have problems with that,  send me a code snippet of what you tried.

**Comment by annbel** [comment]
@rmendels that's great, thanks so much for your help
