### ISSUE TITLE
ncdcOisst21Agg_LonPM180 dataset no longer available?

### ISSUE THREAD

**Issue by dbarneche** [ropensci/rerddap#103]
Hello,

I have been using the dataset ID `ncdcOisst21Agg_LonPM180` for a while now, but today I started getting the following error message on a fresh session:

```
sst_dataset <- "ncdcOisst21Agg_LonPM180"
sst_info <- rerddap::info(sst_dataset)
Error: 'Error {
    code=404;
    message="Not Found: Currently unknown datasetID=ncdcOisst21Agg_LonPM180";
}
' does not exist in current working directory ('/Users...').
```

I've hid the directory name--it was pointing to my project's root directory.
Has this dataset been permanently removed?

Thanks for your help

<details> <summary><strong>Session Info</strong></summary>

```r
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7        xml2_1.3.2        magrittr_2.0.1    rappdirs_0.3.3    tidyselect_1.1.1  R6_2.5.1          rlang_0.4.12     
 [8] rerddap_0.8.0     fansi_0.5.0       dplyr_1.0.7       hoardr_0.5.2      tools_4.1.0       data.table_1.14.2 utf8_1.2.2       
[15] DBI_1.1.1         ellipsis_0.3.2    digest_0.6.27     assertthat_0.2.1  httpcode_0.3.0    tibble_3.1.6      lifecycle_1.0.1  
[22] crayon_1.4.2      purrr_0.3.4       vctrs_0.3.8       triebeard_0.3.0   ncdf4_1.17        curl_4.3.2        crul_1.1.0       
[29] glue_1.5.1        compiler_4.1.0    pillar_1.6.4      urltools_1.7.3    generics_0.1.1    jsonlite_1.7.2    pkgconfig_2.0.3  
```
</details>

**Comment by rmendels** [comment]
@dbarneche It's a long story,  but for now,  try this:

```r
sst_dataset <- "ncdcOisst21Agg_LonPM180"
sst_info <- rerddap::info(sst_dataset, url = 'https://coastwatch.pfeg.noaa.gov/erddap/')
```

and let me know if that does the trick.

**Comment by dbarneche** [comment]
Hi @rmendels , thanks very much for such a quick response!
It is working indeed, though I think it is duplicating existing file names in the cache with new file name. Is that expected?
Thanks!

**Comment by rmendels** [comment]
@dbarneche 

Oh yes,  caching.  Caching is both a boon and a curse in 'rerddap'.    Times like this is more of a curse. To be certain that you are only getting new:

```r
rerddap::cache_delete_all()
```

There is an option to not cache a request, otherwise a hash is made of a requested URL,  and the file is stored in cache,  and if the same URL is given again then the previous result is returned.

**Comment by dbarneche** [comment]
Cheers @rmendels, that did the trick.

**Comment by rmendels** [comment]
@dbarneche 

I should add that cacheing is a particular problem if you use 'last'  in your time.  Then you should always delete cache first.  We warn about this in the docs and the vignettes.
