### ISSUE TITLE
suggestion: add grouping to pkgdown reference index?

### ISSUE THREAD

**Issue by maelle** [ropensci/rerddap#110]
Since https://docs.ropensci.org/rerddap/reference/index.html is a bit long, it might help new users if the functions were grouped by topic. See https://pkgdown.r-lib.org/reference/build_reference.html

**Comment by rmendels** [comment]
@maelle It's taken me awhile since I have been working on other things,  but the reference index is now grouped.  Thanks for pointing me to that.

**Comment by maelle** [comment]
Thank you!!

**Comment by rmendels** [comment]
@maelle Hi Maelle not certain who else to contact.  'rerddap' is now  failing to build for Mac OS X and Linux,  but if I look at the logs there is a failure to download R 4.3.0,  which is independent of 'rerddap'.  It builds fine on my Mac,  and on your Windows.  There is nothing that is platform specific.  Can someone check your build process?

Thanks.

**Comment by rmendels** [comment]
@maelle I should add version 1.0.3 builds fine for all versions on r-universe.

**Comment by maelle** [comment]
@rmendels my first idea would be to update your R-check.yml file: delete it, run `usethis::use_github_action_check_standard()`. Please ping me if that's not enough!

**Comment by maelle** [comment]
Last thing! The dev version of our dev guide has a cheatsheet with in particular ways to get help https://devdevguide.netlify.app/maintenance_cheatsheet.html (pinging me here was ok, but might have been less efficient if I were on vacation for instance :wink:)
