### ISSUE TITLE
new error with `griddap()` in CRAN Release 1.0.2 (vs working in previous 1.0.1): "time must be given as character strings"

### ISSUE THREAD

**Issue by bbest** [ropensci/rerddap#113]
Something funky happened between [CRAN version 1.0.1](https://github.com/ropensci/rerddap/releases/tag/v1.0.1) and the latest [CRAN Release 1.0.2](https://github.com/ropensci/rerddap/releases/tag/v1.0.2).

When fetching data using [CRAN Release 1.0.2](https://github.com/ropensci/rerddap/releases/tag/v1.0.2) with the following:

```r
# install new CRAN Release 1.0.2
devtools::install_github("ropensci/rerddap@b5de651f0186ddfbee6a2f33387b2c07093d348e")

# fetch a commonly used monthly SST dataset for bounding box of Channel Islands and some recently available dates
nc <- rerddap::griddap(
        datasetx  = "jplMURSST41mday",
        fields    = "sst",
        url       = "https://upwell.pfeg.noaa.gov/erddap",
        longitude = c(-123.9999, -123.0824),
        latitude  = c(37.76687, 38.29989),
        time      = c("2023-04-16", "2023-06-16"),
        fmt       = "nc")
```

I get the following error message:

```
[1] "time must be given as character strings"
Error in print.default("you are passing ", paste0(class(dimargs$time))) :
  invalid printing digits -2147483648
In addition: Warning message:
  In print.default("you are passing ", paste0(class(dimargs$time))) :
  NAs introduced by coercion
```
Whereas when using the previous [CRAN version 1.0.1](https://github.com/ropensci/rerddap/releases/tag/v1.0.1) , I get the data returned of interest:

```r
# install previous CRAN Release 1.0.1
devtools::install_github("ropensci/rerddap@6da41ea7a1af990ba880e1988417f4e28de64c5f")

# fetch a commonly used monthly SST dataset for bounding box of Channel Islands and some recently available dates
nc <- rerddap::griddap(
        datasetx  = "jplMURSST41mday",
        fields    = "sst",
        url       = "https://upwell.pfeg.noaa.gov/erddap",
        longitude = c(-123.9999, -123.0824),
        latitude  = c(37.76687, 38.29989),
        time      = c("2023-04-16", "2023-06-16"),
        fmt       = "nc")
nc
```

and I get the legit data

```
<ERDDAP griddap> jplMURSST41mday
   Path: [/var/folders/sl/7s3zmk1129jcrgsn1c4hcs2r0000gn/T//Rtmp1jQvKi/R/rerddap/bcc72a9c047cf1cfffd9e0e328f550b1.nc]
   Last updated: [2023-07-19 14:07:46.026114]
   File size:    [0.07 mb]
   Dimensions (dims/vars):   [3 X 1]
   Dim names: time, latitude, longitude
   Variable names: Sea Surface Temperature Monthly Mean
   data.frame (rows/columns):   [15066 X 4]
# A tibble: 15,066 × 4
   longitude  latitude time                   sst
   <dbl[1d]> <dbl[1d]> <chr>                <dbl>
 1     -124       37.8 2023-04-16T00:00:00Z  11.5
 2     -124.      37.8 2023-04-16T00:00:00Z  11.5
 3     -124.      37.8 2023-04-16T00:00:00Z  11.5
 4     -124.      37.8 2023-04-16T00:00:00Z  11.4
 5     -124.      37.8 2023-04-16T00:00:00Z  11.4
 6     -124.      37.8 2023-04-16T00:00:00Z  11.4
 7     -124.      37.8 2023-04-16T00:00:00Z  11.4
 8     -124.      37.8 2023-04-16T00:00:00Z  11.4
 9     -124.      37.8 2023-04-16T00:00:00Z  11.4
10     -124.      37.8 2023-04-16T00:00:00Z  11.4
# ℹ 15,056 more rows
# ℹ Use `print(n = ...)` to see more rows
```

<details> <summary><strong>Session Info</strong></summary>
` devtools::session_info()`
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.0 (2023-04-21)
 os       macOS Ventura 13.3.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Rome
 date     2023-07-19
 rstudio  2023.06.1+524 Mountain Hydrangea (desktop)
 pandoc   3.1.1 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package        * version    date (UTC) lib source
 abind            1.4-5      2016-07-21 [1] CRAN (R 4.3.0)
 base64enc        0.1-3      2015-07-28 [1] CRAN (R 4.3.0)
 bit              4.0.5      2022-11-15 [1] CRAN (R 4.3.0)
 bit64            4.0.5      2020-08-30 [1] CRAN (R 4.3.0)
 blob             1.2.4      2023-03-17 [1] CRAN (R 4.3.0)
 cachem           1.0.8      2023-05-01 [1] CRAN (R 4.3.0)
 calcofi4r      * 0.7.0      2023-07-19 [1] Github (calcofi/calcofi4r@e9f406f)
 callr            3.7.3      2022-11-02 [1] CRAN (R 4.3.0)
 class            7.3-22     2023-05-03 [1] CRAN (R 4.3.0)
 classInt         0.4-9      2023-02-28 [1] CRAN (R 4.3.0)
 cli              3.6.1      2023-03-23 [1] CRAN (R 4.3.0)
 codetools        0.2-19     2023-02-01 [1] CRAN (R 4.3.0)
 colorspace       2.1-0      2023-01-23 [1] CRAN (R 4.3.0)
 crayon           1.5.2      2022-09-29 [1] CRAN (R 4.3.0)
 crosstalk        1.2.0      2021-11-04 [1] CRAN (R 4.3.0)
 crul             1.4.0      2023-05-17 [1] CRAN (R 4.3.0)
 curl             5.0.1      2023-06-07 [1] CRAN (R 4.3.0)
 data.table       1.14.8     2023-02-17 [1] CRAN (R 4.3.0)
 DBI              1.1.3      2022-06-18 [1] CRAN (R 4.3.0)
 deldir           1.0-9      2023-05-17 [1] CRAN (R 4.3.0)
 devtools         2.4.5      2022-10-11 [1] CRAN (R 4.3.0)
 digest           0.6.33     2023-07-07 [1] CRAN (R 4.3.0)
 dplyr          * 1.1.2      2023-04-20 [1] CRAN (R 4.3.0)
 dygraphs         1.1.1.6    2018-07-11 [1] CRAN (R 4.3.0)
 e1071            1.7-13     2023-02-01 [1] CRAN (R 4.3.0)
 ellipsis         0.3.2      2021-04-29 [1] CRAN (R 4.3.0)
 evaluate         0.21       2023-05-05 [1] CRAN (R 4.3.0)
 extractr       * 0.1.1      2023-07-19 [1] Github (marinebon/extractr@39963fb)
 fansi            1.0.4      2023-01-22 [1] CRAN (R 4.3.0)
 fastmap          1.1.1      2023-02-24 [1] CRAN (R 4.3.0)
 fs             * 1.6.2      2023-04-25 [1] CRAN (R 4.3.0)
 generics         0.1.3      2022-07-05 [1] CRAN (R 4.3.0)
 ggplot2          3.4.2      2023-04-03 [1] CRAN (R 4.3.0)
 glue           * 1.6.2      2022-02-24 [1] CRAN (R 4.3.0)
 gtable           0.3.3      2023-03-21 [1] CRAN (R 4.3.0)
 here           * 1.0.1      2020-12-13 [1] CRAN (R 4.3.0)
 hms              1.1.3      2023-03-21 [1] CRAN (R 4.3.0)
 hoardr           0.5.3      2023-01-26 [1] CRAN (R 4.3.0)
 htmltools        0.5.5      2023-03-23 [1] CRAN (R 4.3.0)
 htmlwidgets      1.6.2      2023-03-17 [1] CRAN (R 4.3.0)
 httpcode         0.3.0      2020-04-10 [1] CRAN (R 4.3.0)
 httpuv           1.6.11     2023-05-11 [1] CRAN (R 4.3.0)
 httr             1.4.6      2023-05-08 [1] CRAN (R 4.3.0)
 httr2            0.2.3      2023-05-08 [1] CRAN (R 4.3.0)
 isoband          0.2.7      2022-12-20 [1] CRAN (R 4.3.0)
 jsonlite         1.8.7      2023-06-29 [1] CRAN (R 4.3.0)
 KernSmooth       2.23-21    2023-05-03 [1] CRAN (R 4.3.0)
 knitr            1.43       2023-05-25 [1] CRAN (R 4.3.0)
 later            1.3.1      2023-05-02 [1] CRAN (R 4.3.0)
 lattice          0.21-8     2023-04-05 [1] CRAN (R 4.3.0)
 lazyeval         0.2.2      2019-03-15 [1] CRAN (R 4.3.0)
 leafem           0.2.0      2022-04-16 [1] CRAN (R 4.3.0)
 leaflet          2.1.2.9000 2023-06-27 [1] Github (rstudio/leaflet@0f8e831)
 librarian        1.8.1      2021-07-12 [1] CRAN (R 4.3.0)
 lifecycle        1.0.3      2022-10-07 [1] CRAN (R 4.3.0)
 lubridate      * 1.9.2      2023-02-10 [1] CRAN (R 4.3.0)
 lwgeom           0.2-13     2023-05-22 [1] CRAN (R 4.3.0)
 magrittr       * 2.0.3      2022-03-30 [1] CRAN (R 4.3.0)
 mapview          2.11.0     2022-04-16 [1] CRAN (R 4.3.0)
 Matrix           1.5-4      2023-04-04 [1] CRAN (R 4.3.0)
 memoise          2.0.1      2021-11-26 [1] CRAN (R 4.3.0)
 mgcv             1.8-42     2023-03-02 [1] CRAN (R 4.3.0)
 mime             0.12       2021-09-28 [1] CRAN (R 4.3.0)
 miniUI           0.1.1.1    2018-05-18 [1] CRAN (R 4.3.0)
 munsell          0.5.0      2018-06-12 [1] CRAN (R 4.3.0)
 ncdf4            1.21       2023-01-07 [1] CRAN (R 4.3.0)
 nlme             3.1-162    2023-01-31 [1] CRAN (R 4.3.0)
 onmsR          * 0.2.2      2023-06-25 [1] Github (noaa-onms/onmsR@ea5c3e5)
 pillar           1.9.0      2023-03-22 [1] CRAN (R 4.3.0)
 pkgbuild         1.4.0      2022-11-27 [1] CRAN (R 4.3.0)
 pkgconfig        2.0.3      2019-09-22 [1] CRAN (R 4.3.0)
 pkgload          1.3.2      2022-11-16 [1] CRAN (R 4.3.0)
 plotly           4.10.1     2022-11-07 [1] CRAN (R 4.3.0)
 png              0.1-8      2022-11-29 [1] CRAN (R 4.3.0)
 polyclip         1.10-4     2022-10-20 [1] CRAN (R 4.3.0)
 prettyunits      1.1.1      2020-01-24 [1] CRAN (R 4.3.0)
 processx         3.8.2      2023-06-30 [1] CRAN (R 4.3.0)
 profvis          0.3.8      2023-05-02 [1] CRAN (R 4.3.0)
 promises         1.2.0.1    2021-02-11 [1] CRAN (R 4.3.0)
 proxy            0.4-27     2022-06-09 [1] CRAN (R 4.3.0)
 ps               1.7.5      2023-04-18 [1] CRAN (R 4.3.0)
 purrr          * 1.0.1      2023-01-10 [1] CRAN (R 4.3.0)
 R.methodsS3      1.8.2      2022-06-13 [1] CRAN (R 4.3.0)
 R.oo             1.25.0     2022-06-12 [1] CRAN (R 4.3.0)
 R.utils          2.12.2     2022-11-11 [1] CRAN (R 4.3.0)
 R6               2.5.1      2021-08-19 [1] CRAN (R 4.3.0)
 rappdirs         0.3.3      2021-01-31 [1] CRAN (R 4.3.0)
 raster           3.6-23     2023-07-04 [1] CRAN (R 4.3.0)
 RColorBrewer     1.1-3      2022-04-03 [1] CRAN (R 4.3.0)
 Rcpp             1.0.11     2023-07-06 [1] CRAN (R 4.3.0)
 readr          * 2.1.4      2023-02-10 [1] CRAN (R 4.3.0)
 remotes          2.4.2      2021-11-30 [1] CRAN (R 4.3.0)
 rerddap          1.0.1      2023-07-19 [1] Github (ropensci/rerddap@6da41ea)
 rlang            1.1.1      2023-04-28 [1] CRAN (R 4.3.0)
 rmarkdown        2.23       2023-07-01 [1] CRAN (R 4.3.0)
 RPostgres        1.4.5      2023-01-20 [1] CRAN (R 4.3.0)
 rprojroot        2.0.3      2022-04-02 [1] CRAN (R 4.3.0)
 rstudioapi       0.15.0     2023-07-07 [1] CRAN (R 4.3.0)
 satellite        1.0.4      2021-10-12 [1] CRAN (R 4.3.0)
 scales           1.2.1      2022-08-20 [1] CRAN (R 4.3.0)
 sessioninfo      1.2.2      2021-12-06 [1] CRAN (R 4.3.0)
 sf             * 1.0-14     2023-07-11 [1] CRAN (R 4.3.0)
 shiny            1.7.4      2022-12-15 [1] CRAN (R 4.3.0)
 sp               2.0-0      2023-06-22 [1] CRAN (R 4.3.0)
 spatstat.data    3.0-1      2023-03-12 [1] CRAN (R 4.3.0)
 spatstat.geom    3.2-2      2023-07-06 [1] CRAN (R 4.3.0)
 spatstat.utils   3.0-3      2023-05-09 [1] CRAN (R 4.3.0)
 stars            0.6-1      2023-04-06 [1] CRAN (R 4.3.0)
 stringi          1.7.12     2023-01-11 [1] CRAN (R 4.3.0)
 stringr        * 1.5.0      2022-12-02 [1] CRAN (R 4.3.0)
 tabularaster     0.7.1      2022-10-18 [1] CRAN (R 4.3.0)
 terra          * 1.7-39     2023-06-23 [1] CRAN (R 4.3.0)
 tibble         * 3.2.1      2023-03-20 [1] CRAN (R 4.3.0)
 tidyr          * 1.3.0      2023-01-24 [1] CRAN (R 4.3.0)
 tidyselect       1.2.0      2022-10-10 [1] CRAN (R 4.3.0)
 timechange       0.2.0      2023-01-11 [1] CRAN (R 4.3.0)
 triebeard        0.4.1      2023-03-04 [1] CRAN (R 4.3.0)
 tzdb             0.4.0      2023-05-12 [1] CRAN (R 4.3.0)
 units            0.8-2      2023-04-27 [1] CRAN (R 4.3.0)
 urlchecker       1.0.1      2021-11-30 [1] CRAN (R 4.3.0)
 urltools         1.7.3      2019-04-14 [1] CRAN (R 4.3.0)
 usethis          2.1.6      2022-05-25 [1] CRAN (R 4.3.0)
 utf8             1.2.3      2023-01-31 [1] CRAN (R 4.3.0)
 vctrs            0.6.3      2023-06-14 [1] CRAN (R 4.3.0)
 viridisLite      0.4.2      2023-05-02 [1] CRAN (R 4.3.0)
 vroom            1.6.3      2023-04-28 [1] CRAN (R 4.3.0)
 webshot          0.5.5      2023-06-26 [1] CRAN (R 4.3.0)
 withr            2.5.0      2022-03-03 [1] CRAN (R 4.3.0)
 xfun             0.39       2023-04-20 [1] CRAN (R 4.3.0)
 xml2             1.3.5      2023-07-06 [1] CRAN (R 4.3.0)
 xtable           1.8-4      2019-04-21 [1] CRAN (R 4.3.0)
 xts              0.13.1     2023-04-16 [1] CRAN (R 4.3.0)
 yaml             2.3.7      2023-01-23 [1] CRAN (R 4.3.0)
 zoo              1.8-12     2023-04-13 [1] CRAN (R 4.3.0)

 [1] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
</details>

**Comment by rmendels** [comment]
@bbest 

```r
 install.packages("rerddap")
Installing package into ‘/Users/rmendels/Library/R/x86_64/4.3/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-x86_64/contrib/4.3/rerddap_1.0.3.tgz'
Content type 'application/x-gzip' length 1619228 bytes (1.5 MB)
==================================================
downloaded 1.5 MB


The downloaded binary packages are in
	/var/folders/46/jyz1mm5x5bvbf59b5g8f7f580000gn/T//RtmpOVFITF/downloaded_packages
> nc <- rerddap::griddap(
+     datasetx  = "jplMURSST41mday",
+     fields    = "sst",
+     url       = "https://upwell.pfeg.noaa.gov/erddap",
+     longitude = c(-123.9999, -123.0824),
+     latitude  = c(37.76687, 38.29989),
+     time      = c("2023-04-16", "2023-06-16"),
+     fmt       = "nc")
> 
> str(nc)
List of 2
 $ summary:List of 15
  ..$ filename   : chr "/var/folders/46/jyz1mm5x5bvbf59b5g8f7f580000gn/T//RtmpOVFITF/R/rerddap/6f97542ce7f9a1aac3e499da93d193b2.nc"
  ..$ writable   : logi FALSE
  ..$ id         : int 65536
  ..$ error      : logi FALSE
```

Install from CRAN.  I will check later on today about the version on GitHub.  I must not have pushed the latest.  The only change in this version is people were giving R times or the like thinking they are characters,  and my general policy is not to second guess what a user really meant,  or they only wanted one time period so were not passing an array of size 2,  all of which failed with no warning.  This was added to catch that and return a proper error.

**Comment by rmendels** [comment]
@bbest Latest version is 1.0.3.  Again,  I am busy this morning but will check later on what is doing with Github version.
