### ISSUE TITLE
Leverage sf?

### ISSUE THREAD

**Issue by cpsievert** [ropensci/rerddap#53]
cc @sckott @rmendels 

The fairly new [sf package](https://github.com/edzer/sfr/) is gaining [lots of traction](https://github.com/hrbrmstr/albersusa/issues/3) and there is even a [new `geom_sf()` coming to **ggplot2**](https://github.com/tidyverse/ggplot2/pull/1990)

Assuming we can represent griddap/tabledap data structures using [simple features](https://cran.r-project.org/web/packages/sf/vignettes/sf1.html), we can leverage/augment some already existing "automatic plotting methods" (e.g., `plot.sf()` and `geom_sf()`).

I'm thinking that (over the next week or so) I will attempt to write some `tabledap`/`griddap_csv`/`griddap_nc` methods for the `sf::st_as_sf()` generic, so generating plots could be as simple as:

```r
library(rerddap)
library(sf)
library(ggplot2)

d <- st_as_sf(tabledap('erdCinpKfmBT'))
plot(d)
ggplot() + geom_sf(data = d)
```

Does this sound reasonable?

**Comment by rmendels** [comment]
It sounds interesting,  I want to look at the quality of the plots, but just that type of simplicity is what I am after.

-Roy

> On Feb 8, 2017, at 2:22 PM, Carson <notifications@github.com> wrote:
> 
> cc @sckott @rmendels
> 
> The fairly new sf package is gaining lots of traction and there is even a new geom_sf() coming to ggplot2
> 
> Assuming we can represent griddap/tabledap data structures using simple features, we can leverage/augment some already existing "automatic plotting methods" (e.g., plot.sf() and geom_sf()).
> 
> I'm thinking that (over the next week or so) I will attempt to write some tabledap/griddap_csv/griddap_nc methods for the sf::st_as_sf() generic, so generating plots could be as simple as:
> 
> library(rerddap
> )
> library(
> sf
> )
> library(
> ggplot2
> )
> 
> 
> d <- st_as_sf(tabledap('erdCinpKfmBT'
> ))
> plot(
> d
> )
> ggplot() 
> + geom_sf(data = d)
> Does this sound reasonable?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.

**Comment by cpsievert** [comment]
@rmendels fyi this has a decent overview of plotting `sf` objects via the `plot()` generic -- http://r-spatial.org/r/2017/01/12/newssf.html

To see some `geom_sf()` examples:

```r
devtools::install_github("tidyverse/ggplot2#1990")
library(ggplot2)
?geom_sf # see examples section
```

**Comment by rmendels** [comment]
Neat.  But can it handle rasters say over the ocean,  or over land as in my examples,  or are you thinking of only using this for table data?
And I have no problem if you build against a feature of ggplot2 that is still only on github.

-Roy

> On Feb 8, 2017, at 3:05 PM, Carson <notifications@github.com> wrote:
> 
> @rmendels fyi this has a decent overview of plotting sf objects via the plot() generic -- http://r-spatial.org/r/2017/01/12/newssf.html
> 
> To see some geom_sf() examples:
> 
> devtools::install_github("tidyverse/ggplot2#1990"
> )
> library(
> ggplot2
> )
> ?
> geom_sf # see examples section
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.

**Comment by sckott** [comment]
can I close this @cpsievert ?

**Comment by cpsievert** [comment]
yep
