### ISSUE TITLE
Data transformation in add_griddap() fails

### ISSUE THREAD

**Issue by rmendels** [ropensci/rerddap#57]
The transformed value is not plotted here (does work in add_tabledap())
library("rerddap")
chlaInfo <- info('erdVHNchla3day')
viirsCHLA <- griddap(chlaInfo, latitude = c(41., 31.), longitude = c(-128., -115), time = c('last','last'), fields = 'chla')
add_griddap(plotdap(), viirsCHLA, ~log2(chla), maxpixels = 50000)

**Comment by sckott** [comment]
is this still an issue @rmendels ? can I close this?

**Comment by rmendels** [comment]
@sckott This is a plotdap issue from when it was still under rerddap  instead of separate, so you can probably close it here.  I am actually working on a bunch of patches for plotdap that have arisen due to changes in other packages, to make it ready for CRAN.  Hope to finalize over the weekend.  Still have to run them by Carson.  The timing requirements for examples on CRAN are almost impossible.  Almost any ggplot2 map will take longer than the desired time.
