### ISSUE TITLE
Possibly break off vis functionality to new pkg

### ISSUE THREAD

**Issue by sckott** [ropensci/rerddap#61]
via #55 

@cpsievert  @rmendels Thoughts on breaking off the vis stuff into a new pkg that depends on `rerddap`?  

The main reason that motivated this issue is: 

- Modularity. There's nice things about separating code into modules that make sense - makes each easier to maintain, they can be maintained independently of one another (while making sure they still play nicely together)

I haven't explored in detail Carson's work, so maybe it would be too hard?  I'm not saying we must do this, just exploring what you two think

**Comment by cpsievert** [comment]
Good idea @sckott! 👍 

I don't think that would be too hard to do. And it would make it much easier for folks (that don't want to use `plotdap()` to install **rerddap**.

**Comment by sckott** [comment]
Cool, @rmendels ?

**Comment by rmendels** [comment]
Yes, that is fine,  I just want the functionality and the ease.  As I said,  the demos we have shown have been very well received.

-Roy

> On May 30, 2017, at 10:39 AM, Scott Chamberlain <notifications@github.com> wrote:
> 
> Cool, @rmendels ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.

**Comment by cpsievert** [comment]
ok, I assume we'd like this to be hosted under the rOpenSci github umbrella? Also, any naming suggestions for the package?

**Comment by cpsievert** [comment]
I suppose **plotdap** would make sense to me. I always get frustrated when the main function in the package doesn't match the package name.

**Comment by sckott** [comment]
doesn't have to be under ropensci - but might make sense for long term sustainability of the two pieces

my only pref. is for all lowercase, no periods

**Comment by rmendels** [comment]
plotdap works for me.  I like what ropensci does,  and we want this to be open

Thanks,

-Roy



> On May 30, 2017, at 11:44 AM, Scott Chamberlain <notifications@github.com> wrote:
> 
> doesn't have to be under ropensci - but might make sense for long term sustainability of the two pieces
> 
> my only pref. is for all lowercase, no periods
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.

**Comment by sckott** [comment]
this is done

**Comment by rmendels** [comment]
Has plotdap been submitted to cran,  or will it be?

Thanks to all. If any I had some more funds ti support further work.

-Roy

> On Jul 17, 2017, at 7:55 PM, Scott Chamberlain <notifications@github.com> wrote:
> 
> this is done
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.

**Comment by sckott** [comment]
I think @cpsievert is still waiting on a new `ggplot2` version?

**Comment by rmendels** [comment]
Thanks.  If I could revisit this,  it would be to see if for the ggplot2 version,  the way the polygons are created and mapped into SF can be improved.  At present you get some artificial "striping" (for want of a better word) when compared to the base graphics version.

But as you can imagine we are just rolling in money,  morale is high,  God’s in His heaven—All’s right with the world! (or the perhaps the more recent version "Ford's in his flivver; all's well with the world".)

-Roy


> On Jul 17, 2017, at 8:24 PM, Scott Chamberlain <notifications@github.com> wrote:
> 
> I think @cpsievert is still waiting on a new ggplot2 version?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.

**Comment by cpsievert** [comment]
I'll submit to CRAN after ggplot2 does.
