### ISSUE TITLE
Give to griddap a vector of specific dates to download

### ISSUE THREAD

**Issue by LuisLauM** [ropensci/rerddap#64]
`griddap` allows to download a range of dates using `time = c(date1, date2)`. That downloads a nc file from date1 to date2, but what if I want to download specific dates like `date1`, `date3`, `date15` and `date17`? Is there a way to download a vector of dates like `c(date1, date3, date15, date17)`?

**Comment by sckott** [comment]
thanks for this @LuisLauM - As the pkg currently stands you can't do that. ERDDAAP servers don't let you AFAIK. 

We can hack together something though, eg.,

```r
foo <- function(x, dates, lat, lon) {
  lapply(dates, function(z) {
    griddap(x, time = rep(z, each = 2), 
            latitude = lat, longitude = lon)
  })
}
dates <- c('2015-12-10', '2015-12-12', '2015-12-23', '2015-12-31')
foo('erdQMekm14day', dates, c(24, 23), c(88, 90))
```

**Comment by sckott** [comment]
closing due to non-response
