### ISSUE TITLE
stricter requirements for percent encoding in URLs

### ISSUE THREAD

**Issue by rmendels** [ropensci/rerddap#72]
Hi Scott:

As we update our Tomcat versions and Java versions,  these are placing  stricter requirements on percent encoding of URLs.  This will break `rerddap` depending on the versions of Tomcat and Java.  You can test these two examples yourself,  they actually eventually point to same dataset on "coastwatch.pfeg.noaa.gov",  they are running the same version of ERDDAP,  what differs is the Tomcat version and Java version.  The example is from your docs.  The first uses the default baseURL "https://upwell.pfeg.noaa.gov/erddap/"

```r
out <- info('erdQMekm14day')
res <- griddap(out,
 time = c('2015-12-28','2016-01-01'),
 latitude = c(24, 23),
 longitude = c(88, 90)
)
Error in R_nc4_open: NetCDF: Unknown file format
Error in ncdf4::nc_open(file) : 
  Error in nc_open trying to open file /var/folders/xw/mcmsdzzx4mgbttplylgs7ysh0000gp/T//Rtmpf5zud5/R/rerddap/ffd709d17957fe0ec89a5a0c16873241.nc
```

Now let's use the base URL "https://coastwatch.pfeg.noaa.gov/erddap/"

```r
out <- info('erdQMekm14day')
res <- griddap(out,
               time = c('2015-12-28','2016-01-01'),
               latitude = c(24, 23),
               longitude = c(88, 90),
               url = "https://coastwatch.pfeg.noaa.gov/erddap/")
res
<ERDDAP griddap> erdQMekm14day
   Path: [/var/folders/xw/mcmsdzzx4mgbttplylgs7ysh0000gp/T//Rtmpf5zud5/R/rerddap/f487b0e3afe0455a5ad3dfbb343d5874.nc]
   Last updated: [2018-06-29 15:29:53]
   File size:    [0.01 mb]
   Dimensions (dims/vars):   [4 X 3]
   Dim names: time, altitude, latitude, longitude
   Variable names: Modulus of Wind Diffusivity Current, Zonal Wind Diffusivity Current, Meridional Wind Diffusivity Current
   data.frame (rows/columns):   [225 X 6]
# A tibble: 225 x 6
   time                   lat   lon mod_current u_current v_current
   <chr>                <dbl> <dbl>       <dbl>     <dbl>     <dbl>
 1 2015-12-28T00:00:00Z  23    88            NA        NA        NA
 2 2015-12-28T00:00:00Z  23    88.2          NA        NA        NA
 3 2015-12-28T00:00:00Z  23    88.5          NA        NA        NA
 4 2015-12-28T00:00:00Z  23    88.8          NA        NA        NA
 5 2015-12-28T00:00:00Z  23    89            NA        NA        NA
 6 2015-12-28T00:00:00Z  23    89.2          NA        NA        NA
 7 2015-12-28T00:00:00Z  23    89.5          NA        NA        NA
 8 2015-12-28T00:00:00Z  23    89.8          NA        NA        NA
 9 2015-12-28T00:00:00Z  23    90            NA        NA        NA
10 2015-12-28T00:00:00Z  23.2  88            NA        NA        NA
# ... with 215 more rows

```

so likely need to URLencode all of the URL's to be certain.

**Comment by rmendels** [comment]
I should clarify.  Just applying the R function `URLencode()` will not do it.  This URL fails in `httr()`

https://upwell.pfeg.noaa.gov/erddap/griddap/erdMBsstd8day.csvp?time[1:1:last]

and will fail if you apply `URLencode()` to the URL.

this URL works in `httr()`

https://upwell.pfeg.noaa.gov/erddap/griddap/erdMBsstd8day.csvp?time%5B0:1:1:last%5D

The following will work using `URLencode()`

```r
urlbase  <-  'https://upwell.pfeg.noaa.gov/erddap/griddap/erdMBsstd8day.csvp?'
url1 <- URLencode('time[1:1:last]', reserved = TRUE)
myURL <- paste(urlbase, url1)
r1 <- httr::GET(myURL)
```
but the package `urltools` seems to do what is expected:

```r
myURL <- urltools::url_encode('https://upwell.pfeg.noaa.gov/erddap/griddap/erdMBsstd8day.csvp?time[1:1:last]')
r1 <- GET(myURL)
str(r1$content)
 raw [1:246] 3c 21 44 4f ...

```

**Comment by sckott** [comment]
thanks very much @rmendels - will look into this soon

**Comment by rmendels** [comment]
After running the most recent version of Tomcat for a while, we kept on seeing problems and reverted to an earlier version,  and now things reported above work again.  We are not certain exactly what changes have been made in Tomcat,  but clearly they are changing percent encoding requirements and how that is done.  In the long run insuring proper percent encoding will be important,  as down the line we will have to switch back to a more up-to-date version of Tomcat as we get scanned every weekend and get dinged after awhile. It does appear that the urltools function does a better job of it.

**Comment by sckott** [comment]
thanks @rmendels

**Comment by sckott** [comment]
@rmendels is this still a problem. i can't replicate any problems as is right now.

**Comment by rmendels** [comment]
Hi Scott:

Yes and no if it is still a problem.  For our servers it is not a problem at the moment,  because we reverted to earlier versions of Tomcat.  When we move to some of the newer versions we will be getting around this by adding "Add a new parameter: relaxedQueryChars='[]|' " to our connection port in Tomcat, which eliminates the problem, and other sites are doing the same thing,  as the THREDDS Data Server has the same issue.  Down the line,  based on the last few years,  Tomcat has been getting stricter and stricter about what it will accept for percent encoding.  Certainly at this point it is lower in priority,  but something to keep in mind,  and also keep in mind that it does appear that urltools::url_encode() does a more up-to-date job of percent encoding than does the function in Base R.

**Comment by rmendels** [comment]
not that i am aware of.  this has been causing all sorts of problems for a number of servers,  most people have applied the fix i mentioned.

**Comment by leomarameo7** [comment]
Hi everyone, 
I have the same error message 

> Error in ncdf4::nc_open(file) : 
  Error in nc_open trying to open file /Users/leonardocapitani/Library/Caches/R/rerddap/fd4c4c271d0d276e0b89b0a0c0003186.nc

 when I try to download SST data with this command:
```
ymx <- griddap(x = "jplMURSST41",
               time = c('2008-01-01', '2013-12-31'),
               latitude = c(20.64, 20.65),
               longitude = c(-87.04, -87.05),
               url = "https://coastwatch.pfeg.noaa.gov/erddap/", 
               fields = "analysed_sst")$data
```
Does anyone help me with this error? Thank you all for the time and pleasure. 

`sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rerddap_0.6.5   lubridate_1.7.9 forcats_0.5.0   stringr_1.4.0   dplyr_1.0.2    
 [6] purrr_0.3.4     tidyr_1.1.2     tibble_3.0.3    ggplot2_3.3.2   tidyverse_1.3.0
[11] readr_1.3.1    

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.0  reshape2_1.4.4    haven_2.2.0       lattice_0.20-41  
 [5] colorspace_1.4-1  vctrs_0.3.4       generics_0.0.2    rlang_0.4.7      
 [9] pillar_1.4.6      glue_1.4.2        httpcode_0.3.0    withr_2.3.0      
[13] DBI_1.1.0         rappdirs_0.3.1    dbplyr_1.4.3      modelr_0.1.6     
[17] readxl_1.3.1      lifecycle_0.2.0   plyr_1.8.6        munsell_0.5.0    
[21] gtable_0.3.0      cellranger_1.1.0  rvest_0.3.5       curl_4.3         
[25] hoardr_0.5.2      fansi_0.4.1       triebeard_0.3.0   urltools_1.7.3   
[29] broom_0.5.6       Rcpp_1.0.5        scales_1.1.1      backports_1.1.10 
[33] jsonlite_1.7.1    fs_1.4.1          hms_0.5.3         digest_0.6.25    
[37] stringi_1.5.3     ncdf4_1.17        grid_4.0.3        cli_2.0.2        
[41] tools_4.0.3       magrittr_1.5      crul_1.0.0        crayon_1.3.4     
[45] pkgconfig_2.0.3   ellipsis_0.3.1    data.table_1.13.0 xml2_1.3.2       
[49] reprex_0.3.0      assertthat_0.2.1  httr_1.4.2        rstudioapi_0.11  
[53] R6_2.4.1          nlme_3.1-149      compiler_4.0.3 `

**Comment by rmendels** [comment]
@leomarameo7  @sckott 

please rerun with the verbose option set and post the output.  I can think of several reasons,  including we have had to do some upgrades the lat few days and you may have just hit a downtime  That is one advantage of doing the rerddap::info() command first,  it checks if the dataset is available.

**Comment by leomarameo7** [comment]
Thanks Roy for the reply. First I've checked `rerddap::info("jplMURSST41")` and I've got 

> <ERDDAP info> jplMURSST41 
 Base URL: https://upwell.pfeg.noaa.gov/erddap/ 
 Dataset Type: griddap 
 Dimensions (range):  
     time: (2002-06-01T09:00:00Z, 2020-12-16T09:00:00Z) 
     latitude: (-89.99, 89.99) 
     longitude: (-179.99, 180.0) 
 Variables:  
     analysed_sst: 
         Units: degree_C 
     analysis_error: 
         Units: degree_C 
     mask: 
     sea_ice_fraction: 
         Units: 1 

So it seems that the dataset is available. Isn't it? 
Second I've added the verbose option `callopts = list(verbose = TRUE)` as you've suggested. I've run and the error message is the same: 

> Error in R_nc4_open: NetCDF: Unknown file format
Error in ncdf4::nc_open(file) : 
  Error in nc_open trying to open file /Users/leonardocapitani/Library/Caches/R/rerddap/fd4c4c271d0d276e0b89b0a0c0003186.nc

**Comment by rmendels** [comment]
@leomarameo7 @sckott There should have been verbose output from trying to get the file.  That is what I need to see.  If you are not getting verbose output,  that means you have a bad file in your rerddap cache.  Clear your cache.  Then run with verbose.  It should show the calls being made,  and more importantly any errors being returned by the service.

**Comment by leomarameo7** [comment]
With your help, I've solved the problem. It was just that: cleaning the cache. The code runs without errors. Thank you very much, Roy.

**Comment by rmendels** [comment]
@leomarameo7 @sckott Glad I could help.  If I had to guess, you ran once when we were doing some upgrades,  and instead of a netcdf file what was downloaded was a file with with an http error.  With that in your cache,  every time you re-tried the same command,  it just tried to re-open the cached file.  Always glad to help,  but as a rule,  you can help me if something doesn't work by first making certain that you run rerddap:info() to see if it shows the dataset,  and if does,  then run in verbose mode,  and supply the output.  The latter can often,  but not always,  provide me some of the information I need.
