### ISSUE TITLE
latitudes running north-south fix

### ISSUE THREAD

**Issue by rmendels** [ropensci/rerddap#78]
@sckott Just ran into a situation where the present grid.R fails for a north-south latitude.  The problem is they have lat_min as -89 and lat_max as 89,  but actual range as (89, -89) with spacing as a negative number.  Our feeling is that according to CF standards that is incorrect,  but we can't make a provider set things up as we think it should be  (though in this case we are having discussions with them). You actually check for both,  and reverse latitudes twice.  You can see the problem in this example:

```r
extract <- griddap("noaacwNPPVIIRSchlaMonthly",
            fields = 'chlor_a',
            time = c("2019-01-16T12:00:00Z", "2019-01-16T12:00:00Z"),
            altitude = c(0, 0),
            latitude = c(30, 40),
            longitude = c(-120, -105),
            url = "https://coastwatch.noaa.gov/erddap/"
            )
```

I would suggest the following fix in grid.R.  Starting at line 205, you presently have:

```r
    ## new
    if (nm %in% c('latitude', 'longitude')) {
      z <- unlist(strsplit(.info$alldata[[nm]]$value[1], ","))
      spacing <- as.numeric(unlist(strsplit(z[3], "=")[[1]])[2])
      if (spacing < 0) {
          dimargs[[i]] <- rev(dimargs[[i]])
      }
    }
  }
  dimargs
}
```

replace with

```r
    ## new
    if (nm %in% c('latitude', 'longitude')) {
      z <- unlist(strsplit(.info$alldata[[nm]]$value[1], ","))
      spacing <- as.numeric(unlist(strsplit(z[3], "=")[[1]])[2])
      if (spacing < 0) {
        if (!(dimargs[[i]][1] > dimargs[[i]][2])) {
          dimargs[[i]] <- rev(dimargs[[i]])
        }
      }
    }
  }
  dimargs
}
```

The example will then work.

**Comment by sckott** [comment]
thanks @rmendels for this

i'll have a look soon

**Comment by rmendels** [comment]
@sckott I should add that it turns out that they are using an older version of ERDDAP,  which is causing the problem.  What you had works with the newer version, which is what we run.  But can't guarantee people will be running newer version,  I believe the one line patch will work with both cases and is a minimal change.

**Comment by sckott** [comment]
ok
