### ISSUE TITLE
Include url in info

### ISSUE THREAD

**Issue by rmendels** [ropensci/rerddap#80]
@sckott - as long as you might be making changes and resubmitting to CRAN,  can you modify info.R to include the URL of the call.  All that is need is to add one thing in info.R.  Lines 103-107 presently read:

```r
  structure(list(variables=vars, alldata=oo),
            class="info",
            datasetid=datasetid,
            type=table_or_grid(datasetid))
}
```

Just change to:

```r
  structure(list(url = url, variables=vars, alldata=oo),
            class="info",
            datasetid=datasetid,
            type=table_or_grid(datasetid))
}
```

**Comment by sckott** [comment]
sure, can do, but why do you want the URL? 

to be sure, what URL do you want: e.g., in this call 

```r
info('erdATastnhday')
```

This is the URL that was used to do the HTTP call:

https://upwell.pfeg.noaa.gov/erddap/info/erdATastnhday/index.json

is that the URL you want or a different one?

**Comment by rmendels** [comment]
@sckott - The idea is to make the return from `rerddap::info()` self-contained.  If this is added,  if a user passes me the result from  `rerddap::info()`, I know the base ERDDAP URL that was used to obtain the result.  So rather than requiring the user to pass that to me again,  it is now self-contained in the return of `rerddap::info()`.  So in the case you give,  the URL would be:

https://upwell.pfeg.noaa.gov/erddap/

I actually brought this up once before.  I believe the small patch above correctly includes the URL I am after.

**Comment by sckott** [comment]
Okay, so the base url for the ERDDAP server, can do

**Comment by sckott** [comment]
okay, its added

**Comment by rmendels** [comment]
@sckott Thanks.
