### ISSUE TITLE
bug in griddap, returns empty object

### ISSUE THREAD

**Issue by afredstonhermann** [ropensci/rerddap#81]
I haven't used rerddap in a few months and now when I use griddap for any query, it returns an empty object with two columns, "summary" and "data". This occurs with multiple datasets I am trying to use and also with the griddap example in the rerddap vignette: https://cran.r-project.org/web/packages/rerddap/vignettes/Using_rerddap.html

I was able to reproduce this error with both the CRAN and development versions of rerddap, and on my local machine as well as an RStudio server: 

```
> library(rerddap)
> sstInfo <- info('jplMURSST41')
> murSST <- griddap(sstInfo, latitude = c(22., 51.), longitude = c(-140., -105), time = c("2017-01-01", "2017-01-02"), fields = 'analysed_sst')
> dim(murSST)
[1] 0 2
> colnames(murSST)
[1] "summary" "data"   
> View(murSST)
Error in View : arguments imply differing number of rows: 0, 20312802
```

**Comment by sckott** [comment]
thanks for the issue!

I tried with the CRAN version and the development version here, same result both ways. 

The resulting output has changed to make certain things easier. 

- if you ask for netcdf data, `fmt = "nc"` (the default) you get a list back, with slots for `summary` and `data`. `summary` is the output from `ncdf4::nc_open` (opening a netcdf file) and `data` is the data.frame created from that netcdf file. to get the data.frame you just need to index to it like `murSST$data`
- if you ask for csv data, `fmt = "csv` you get a data.frame back, with a modified print of that data.frame

**Comment by sckott** [comment]
i do see that the return value for `griddap` can be improved, so will do that

**Comment by afredstonhermann** [comment]
Genius! Thank you and thanks for developing this package, it's a fantastic resource. 

To make it easy for future readers, to get data from griddap following the example code in the vignette, just add $data: 

    murSST <- griddap(sstInfo, latitude = c(22., 51.), longitude = c(-140., -105), time = c("2017-01-01", "2017-01-02"), fields = 'analysed_sst')$data
