### ISSUE TITLE
griddap drops depth/altitude dimension

### ISSUE THREAD

**Issue by afredstonhermann** [ropensci/rerddap#82]
I'm querying a dataset where the dimensions are time, lat, lon, and depth, and assorted measured variables. When I run `griddap` for this dataset, the output does not retain the depth dimension. Is it possible to keep depth in the query? I would guess that dropping the depth/altitude dimension is a feature to simplify the output (since in vignettes and other use cases it doesn't appear in the output either) but it is important for my research questions. Depth is listed as a dimension in the `summary` of the `griddap` output, and by manually exploring the dataset on the ERDDAP website I can confirm that there are real depth values in there. 

Here's what I'm trying to do: 
```
latrange <- c(35.,48.)
lonrange <- c(-78.,-60.)
depthrange <- c(5.04, 400.) # cutting off depth query at shelf; min value comes from data attributes 
code.3.3.1 <- "erdSoda331oceanmday_LonPM180"
daterange <- c('2001-01-16','2001-12-16')
out <- griddap(code.3.3.1, latitude = latrange, longitude = lonrange, time = daterange, depth = depthrange, fields = "temp")$data
```

But when I run this, `out` only has 4 columns: latitude, longitude, time, and temp.

**Comment by sckott** [comment]
thanks, having a look

**Comment by sckott** [comment]
we weren't parsing additional dimension variables beyond time/lat/lon, there may still be other edge cases, but this should work for any additional dimensions. reinstall `remotes::install_github("ropensci/rerddap")`, reload R, and try again please

**Comment by afredstonhermann** [comment]
That worked perfectly, it now returns the depth dimension. Thank you!
