### ISSUE TITLE
cmocean

### ISSUE THREAD

**Issue by rmendels** [ropensci/rerddap#84]
@sckott  very low priority,  but sometime when you have time to kill can I suggest dumping the the colors in the file "colors.RData" and instead using the `R` package `cmocean`.  the `cmocean` colors are what I translated to `R` format,  the package has the advantage that Kristen Thyng is one of the authors,  she is the developer of the `cmocean` colors,  and it is more likely to be kept up to date with changes she makes.

**Comment by sckott** [comment]
sounds good, will do

**Comment by rmendels** [comment]
I just realized that almost all the use the colors is in the Vignette.  So that puts the onus on me.

**Comment by sckott** [comment]
ok
