### ISSUE TITLE
Use a canonical list of Erddap locations

### ISSUE THREAD

**Issue by adamml** [ropensci/rerddap#86]
Referencing https://github.com/IrishMarineInstitute/search-erddaps/issues/4 and https://github.com/ioos/erddapy/issues/92, there is a move to consolidate on a canonical list of Erddap locations for tools searching across multiple Erddap locations.

Can you support this?

**Comment by sckott** [comment]
thanks. Ours is here https://github.com/ropensci/rerddap/blob/master/R/servers.R - Would be happy to use a more centrally maintained list of ERDDAP locations. I'd prefer a json file over a js file, but probably either works

**Comment by adamml** [comment]
Thanks @sckott.

I used yours, @bobsimons’ list, and the one from erddapy in generating the list on our repo.

There is a .json file, see https://github.com/IrishMarineInstitute/awesome-erddap/blob/master/erddaps.json

We also set up github-pages, so the json can be accessed at  https://irishmarineinstitute.github.io/awesome-erddap/erddaps.json

**Comment by sckott** [comment]
nice, i'll probably use the gh-pages link.
