### ISSUE TITLE
Problem with jplMURSST41, undetailed error

### ISSUE THREAD

**Issue by LuisLauM** [ropensci/rerddap#96]
When I try to use the griddap function with a specific source (MUR), it just returns the word ERROR, without any detail. It also happens with other sources, but after a while it works. I have tested from different PC and different networks.

```r
varID <- "jplMURSST41"

info(datasetid = varID)

griddap(x = varID,
        time = c("2010-01-01", "2010-01-31"),
        latitude = c(-25, 10),
        longitude = c(-100, -70),
        fields = "analysed_sst",
        read = FALSE)

```
<details> <summary><strong>Session Info</strong></summary>

```r
 setting  value                       
 version  R version 4.0.4 (2021-02-15)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Spanish_Peru.1252           
 ctype    Spanish_Peru.1252           
 tz       America/Bogota              
 date     2021-03-03  

```

</details>

**Comment by sckott** [comment]
Thanks, but that is not your R session info. Please share your R session info, output of `sessioninfo::session_info()`

**Comment by LuisLauM** [comment]
My mistake, yes. I have edited my first post.

**Comment by sckott** [comment]
Should be fixed now. First, see `cache_info()$path`, go to that path and delete all files in there so that the next `griddap` request doesn't use the cached file. 

Then try again and you should get a useful error message. Let me know what happens

**Comment by LuisLauM** [comment]
> Should be fixed now. First, see `cache_info()$path`, go to that path and delete all files in there so that the next `griddap` request doesn't use the cached file.
> 
> Then try again and you should get a useful error message. Let me know what happens

Yes, it is working properly now. Thank you.
