### ISSUE TITLE
Error with jplMURSST41

### ISSUE THREAD

**Issue by grwhumphries** [ropensci/rerddap#98]
Hi,  I'm using R v 4.0.3, and rerrdap v 0.7.4 and until now I could call the jplMURSST version 4.1 data using:   

```r
dataInfo <- info('jplMURSST41')
```

However, this is now producing the error 

```r
Error: 'Error {
    code=404;
    message="Not Found: Currently unknown datasetID=jplMURSST41";
}
```
Using simply 'jplMURSST' works fine, but that's not giving access to the v 4.1 data that we use normally. 

Is this an ERDDAP issue, or did something change elsewhere?

**Comment by sckott** [comment]
thanks for opening the issue 

That example works for me. Is it still not working for you? If so, please share your session info
