### ISSUE TITLE
2015 missing for erdMH1sstd1dayR20190SQ

### ISSUE THREAD

**Issue by schckngs** [ropensci/rerddap#99]
Hey, I have been making weekly SST climatology layers from the MODISA science-quality product available on the CoastWatch ERDDAP server ("erdMH1sstd1dayR20190SQ"). It looks like a great deal of 2015 is missing.

```
sstvar = info("erdMH1sstd1dayR20190SQ", url = "https://coastwatch.pfeg.noaa.gov/erddap/")
timelim = c("2015-05-06", "2015-05-12")
sstdata <- griddap(sstvar, latitude = c(30,61.5),
                   longitude =  c(-160,-120), 
                   time = timelim)
                   
>unique(sstdata$data$time)
[1] "2014-12-31T12:00:00Z"
```
I haven't tried the whole year, but looking at other weeks produces different results (closest timestamp available?)

```
timelim = c("2015-06-06", "2015-06-12")
sstdata <- griddap(sstvar, latitude = c(30,61.5),
                   longitude =  c(-160,-120), 
                   time = timelim)

>unique(sstdata$data$time)
[1] "2015-10-16T12:00:00Z"
```

Thanks for maintaining this package, it's so useful!!
Cheers.

<details> <summary><strong>Session Info</strong></summary>

```r
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.7.9.2 dplyr_1.0.2       rerddap_0.7.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        xml2_1.3.2        magrittr_2.0.1    maps_3.3.0       
 [5] rappdirs_0.3.1    tidyselect_1.1.0  colorspace_2.0-0  R6_2.5.0         
 [9] rlang_0.4.10      hoardr_0.5.2      tools_4.0.2       dichromat_2.0-0  
[13] data.table_1.13.2 ellipsis_0.3.1    digest_0.6.27     httpcode_0.3.0   
[17] tibble_3.0.4      lifecycle_1.0.0   crayon_1.4.1      mapproj_1.2.7    
[21] purrr_0.3.4       pals_1.6          vctrs_0.3.5       triebeard_0.3.0  
[25] curl_4.3          ncdf4_1.17        crul_1.0.0        glue_1.4.2       
[29] compiler_4.0.2    pillar_1.4.7      urltools_1.7.3    generics_0.1.0   
[33] jsonlite_1.7.2    pkgconfig_2.0.3  
```
</details>

**Comment by sckott** [comment]
Sorry for the delay, having a look now

**Comment by sckott** [comment]
@rmendels Perhaps you can help here. I'm not sure why we are ending up with the wrong results for these queries.

```r
library(rerddap)
crul::set_verbose()
sstvar <- info("erdMH1sstd1dayR20190SQ", url = "https://coastwatch.pfeg.noaa.gov/erddap/")
timelim <- c("2015-05-06", "2015-05-12")
sstdata <- griddap(sstvar, latitude = c(30,61.5),
                   longitude =  c(-160,-120), 
                   time = timelim)
unique(sstdata$data$time)
[1] "2014-12-31T12:00:00Z"
```

The HTTP request for the above `griddap()` request is 

```
/erddap/griddap/erdMH1sstd1dayR20190SQ.nc?sstMasked[(2015-05-06):1:(2015-05-12)][(61.5):1:(30)][(-160):1:(-120)]
```

I think it's correctly formatted, but the data given back does not have data with dates in the range of that requested. 

Any ideas? Seems like the same thing happens on the website query interface.

**Comment by rmendels** [comment]
@sckott 

The reason is that the there appears to be a gap in that dataset, and you hit it.  Here are the list of times around that:


2014-12-30T12:00:00Z
2014-12-31T12:00:00Z
2015-10-16T12:00:00Z
2015-10-17T12:00:00Z
2015-10-18T12:00:00Z
2015-10-19T12:00:00Z
2015-10-20T12:00:00Z
2015-10-21T12:00:00Z

ERDDAP returns the "closest" value in that case.  Not certain why the gap,  and that may take me a number of days to figure out what is going on and see how if I can fill in the gap. The main thing is in terms of how ERDDAP works,  'rerddap' is returning the correct response.

**Comment by rmendels** [comment]
@sckott 

I filled-in the data gap overnight.  That code should now give the expected return.  Thanks for catching this.

**Comment by sckott** [comment]
Great, thanks @rmendels , now works

@schckngs try it again, should work now

**Comment by schckngs** [comment]
Thank you very much @rmendels!! 
Cheers, closing this issue.

**Comment by schckngs** [comment]
Hi, I am returning to this thread as I have come across more missing data in this record. The AVHRR Pathfinder SST is current to 2021-06-30 though is only current to 2020-12-31 on the ERDDAP server.
Apologies if this isn't the right place to ask for help (maybe I should use the contact on the CoastWatch server site)! I'm inclined to post here as you folks have been very responsive. 
Cheers.

**Comment by rmendels** [comment]
@schckngs  Not really an rerddap issue.  I am now the maintainer,  but it is a more a question for our group in ERD.  Please email me directly at roy.mendelssohn@noaa as I don't have your direct email.

**Comment by rmendels** [comment]
@schckngs Sorry that should be roy.mendelssohn@noaa.gov
